name       : libxext
version    : 1.3.4
release    : 14
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXext-1.3.4.tar.gz : 8ef0789f282826661ff40a8eef22430378516ac580167da35cc948be9041aac1
license    : MIT
component  : xorg.library
summary    : X11 common extensions base
description: |
    library for common extensions to the X11 protocol
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig(xproto)
    - pkgconfig32(x11)
patterns   :
    - devel :
        - /usr/share/man
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
