name       : libxext
version    : 1.3.5
release    : 16
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXext-1.3.5.tar.gz : 1a3dcda154f803be0285b46c9338515804b874b5ccc7a2b769ab7fd76f1035bd
license    : MIT
component  : xorg.library
summary    : X11 common extensions base
description: |
    library for common extensions to the X11 protocol
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig(xproto)
    - pkgconfig32(x11)
patterns   :
    - devel :
        - /usr/share/man
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
