name       : libxext
version    : 1.3.3
release    : 11
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXext-1.3.3.tar.bz2 : b518d4d332231f313371fdefac59e3776f4f0823bcb23cf7c7305bfb57b16e35
license    :
    - MIT
summary    : X11 common extensions base
component  : xorg.library
builddeps  :
    - pkgconfig(xextproto)
    - pkgconfig(x11)
    - pkgconfig32(x11)
emul32     : yes
optimize   : speed
patterns   :
    - devel :
        - /usr/share/man
description: |
    library for common extensions to the X11 protocol
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
